apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  # cat ~/.aws/credentials | head -n 3 | base64
  aws_access_key_id: QVNJQTZPSFdUSFAzWkJOUUs0VTQ=
  aws_secret_access_key: SG5XWm9PQk1WTjhRbmdmYVBBa0duVEFiM0JoV2NMQXJQQ3VBSEZMdg==
  aws_session_token : RndvR1pYSXZZWGR6RUxyLy8vLy8vLy8vL3dFYURPMUlnZk1URjFHUzdVR0RqQ0xWQVRVaXcvSUQ5VW10bC94MXRIL05hUEtGSXl2MDZPU1ZqRVFoeittTWEzRHZxM1lQY1dVZDBuQVRUcHhTQjdZMndnTGlDTy9RaHdLYzFTdFBXbDJBOVNBSnQwbTlLQkxyNHFOdWJVQWJ3UTVrV1VDbTFzc1RFMExtU3FjOXcvRlNBZ3I1MFdwNkVRWUd1TWxUQkhqVDlKdlBCa1EzRlE0cGV6VEx4c0FYU3VyOVdJMlNlcThVRU9Vd213b3pPdmJrVUhVK0ZubUZ1cmZJQ3VsNENNRkJJci9CV2c3UzF0c1dzeDc5TUl0RUN3NXhwYzJaV0d3K24zVXJMb0RINExOeUJzWTUyMFpxZldySmc3eWxCdGF2U3MrTlFnT3BnQ2lMa2VhY0JqSXRNM0s4TlFvUGc0M1JVT3pmV2owVjZkWmhqZDFodFBCemNGRldtMDArb0tlQlVTTFk1Nzdta0JwWjlYRlA=