apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "6"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"service":"backend-feed"},"name":"backend-feed","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"service":"backend-feed"}},"template":{"metadata":{"labels":{"service":"backend-feed"}},"spec":{"containers":[{"env":[{"name":"URL","valueFrom":{"configMapKeyRef":{"key":"URL","name":"env-config"}}},{"name":"AWS_BUCKET","valueFrom":{"configMapKeyRef":{"key":"AWS_BUCKET","name":"env-config"}}},{"name":"AWS_PROFILE","valueFrom":{"configMapKeyRef":{"key":"AWS_PROFILE","name":"env-config"}}},{"name":"AWS_REGION","valueFrom":{"configMapKeyRef":{"key":"AWS_REGION","name":"env-config"}}},{"name":"JWT_SECRET","valueFrom":{"configMapKeyRef":{"key":"JWT_SECRET","name":"env-config"}}},{"name":"POSTGRES_DB","valueFrom":{"configMapKeyRef":{"key":"POSTGRES_DB","name":"env-config"}}},{"name":"POSTGRES_HOST","valueFrom":{"configMapKeyRef":{"key":"POSTGRES_HOST","name":"env-config"}}},{"name":"POSTGRES_PASSWORD","valueFrom":{"secretKeyRef":{"key":"POSTGRES_PASSWORD","name":"env-secret"}}},{"name":"POSTGRES_USERNAME","valueFrom":{"secretKeyRef":{"key":"POSTGRES_USERNAME","name":"env-secret"}}}],"image":"huy56xf/udagram-api-feed:v1","name":"backend-feed","resources":{"limits":{"cpu":"500m","memory":"1024Mi"},"requests":{"cpu":"250m","memory":"64Mi"}},"volumeMounts":[{"mountPath":"/root/.aws/","name":"aws-secret","readOnly":true}]}],"serviceAccountName":"default-sa","volumes":[{"name":"aws-secret","secret":{"secretName":"aws-secret"}}]}}}}
    creationTimestamp: "2022-04-08T05:36:54Z"
    generation: 8
    labels:
      service: backend-feed
    name: backend-feed
    namespace: default
    resourceVersion: "113120"
    uid: 5935bedf-b1c9-468f-92e1-78178fa3b547
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        service: backend-feed
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2022-04-08T13:26:20Z"
        creationTimestamp: null
        labels:
          service: backend-feed
      spec:
        containers:
        - env:
          - name: URL
            valueFrom:
              configMapKeyRef:
                key: URL
                name: env-config
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                key: AWS_BUCKET
                name: env-config
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                key: AWS_PROFILE
                name: env-config
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                key: AWS_REGION
                name: env-config
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                key: JWT_SECRET
                name: env-config
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DB
                name: env-config
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_HOST
                name: env-config
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: env-secret
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USERNAME
                name: env-secret
          image: huy56xf/udagram-api-feed:v1
          imagePullPolicy: Always
          name: backend-feed
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /root/.aws/
            name: aws-secret
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: default-sa
        serviceAccountName: default-sa
        terminationGracePeriodSeconds: 30
        volumes:
        - name: aws-secret
          secret:
            defaultMode: 420
            secretName: aws-secret
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-04-08T05:36:54Z"
      lastUpdateTime: "2022-04-08T14:29:40Z"
      message: ReplicaSet "backend-feed-5896f8965d" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2022-04-08T14:42:44Z"
      lastUpdateTime: "2022-04-08T14:42:44Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 8
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "6"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"service":"backend-user"},"name":"backend-user","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"service":"backend-user"}},"template":{"metadata":{"labels":{"service":"backend-user"}},"spec":{"containers":[{"env":[{"name":"URL","valueFrom":{"configMapKeyRef":{"key":"URL","name":"env-config"}}},{"name":"JWT_SECRET","valueFrom":{"configMapKeyRef":{"key":"JWT_SECRET","name":"env-config"}}},{"name":"POSTGRES_DB","valueFrom":{"configMapKeyRef":{"key":"POSTGRES_DB","name":"env-config"}}},{"name":"POSTGRES_HOST","valueFrom":{"configMapKeyRef":{"key":"POSTGRES_HOST","name":"env-config"}}},{"name":"POSTGRES_PASSWORD","valueFrom":{"secretKeyRef":{"key":"POSTGRES_PASSWORD","name":"env-secret"}}},{"name":"POSTGRES_USERNAME","valueFrom":{"secretKeyRef":{"key":"POSTGRES_USERNAME","name":"env-secret"}}}],"image":"huy56xf/udagram-api-user:v1","name":"backend-user","resources":{"limits":{"cpu":"500m","memory":"1024Mi"},"requests":{"cpu":"250m","memory":"64Mi"}},"volumeMounts":[{"mountPath":"/root/.aws/","name":"aws-secret","readOnly":true}]}],"serviceAccountName":"default-sa","volumes":[{"name":"aws-secret","secret":{"secretName":"aws-secret"}}]}}}}
    creationTimestamp: "2022-04-08T05:36:55Z"
    generation: 8
    labels:
      service: backend-user
    name: backend-user
    namespace: default
    resourceVersion: "113163"
    uid: 471c47eb-8c54-4be1-908c-043e48ffdb4e
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        service: backend-user
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2022-04-08T13:26:24Z"
        creationTimestamp: null
        labels:
          service: backend-user
      spec:
        containers:
        - env:
          - name: URL
            valueFrom:
              configMapKeyRef:
                key: URL
                name: env-config
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                key: JWT_SECRET
                name: env-config
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DB
                name: env-config
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_HOST
                name: env-config
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: env-secret
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USERNAME
                name: env-secret
          image: huy56xf/udagram-api-user:v1
          imagePullPolicy: Always
          name: backend-user
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /root/.aws/
            name: aws-secret
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: default-sa
        serviceAccountName: default-sa
        terminationGracePeriodSeconds: 30
        volumes:
        - name: aws-secret
          secret:
            defaultMode: 420
            secretName: aws-secret
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-04-08T05:36:55Z"
      lastUpdateTime: "2022-04-08T14:30:12Z"
      message: ReplicaSet "backend-user-58c5bc5f7" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2022-04-08T14:42:52Z"
      lastUpdateTime: "2022-04-08T14:42:52Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 8
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "8"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"service":"frontend"},"name":"frontend","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"service":"frontend"}},"template":{"metadata":{"labels":{"api":"external","service":"frontend"}},"spec":{"containers":[{"image":"huy56xf/udagram-frontend:v1","name":"frontend","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"500m","memory":"1024Mi"},"requests":{"cpu":"250m","memory":"64Mi"}}}],"serviceAccountName":"default-sa"}}}}
    creationTimestamp: "2022-04-08T05:37:01Z"
    generation: 12
    labels:
      service: frontend
    name: frontend
    namespace: default
    resourceVersion: "106053"
    uid: 73e357db-5a30-46ca-bf85-fd698e56ec3a
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        service: frontend
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2022-04-08T13:08:26Z"
        creationTimestamp: null
        labels:
          api: external
          service: frontend
      spec:
        containers:
        - image: huy56xf/udagram-frontend:v5
          imagePullPolicy: Always
          name: frontend
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: default-sa
        serviceAccountName: default-sa
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-04-08T05:37:01Z"
      lastUpdateTime: "2022-04-08T13:51:23Z"
      message: ReplicaSet "frontend-6694f4db5d" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2022-04-08T14:01:45Z"
      lastUpdateTime: "2022-04-08T14:01:45Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 12
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"service":"reverseproxy"},"name":"reverseproxy","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"service":"reverseproxy"}},"template":{"metadata":{"labels":{"service":"reverseproxy"}},"spec":{"containers":[{"image":"huy56xf/udagram-reverseproxy:v1","name":"reverseproxy","ports":[{"containerPort":8001}],"resources":{"limits":{"cpu":"500m","memory":"1024Mi"},"requests":{"cpu":"250m","memory":"64Mi"}}}],"serviceAccountName":"default-sa"}}}}
    creationTimestamp: "2022-04-08T05:37:03Z"
    generation: 5
    labels:
      service: reverseproxy
    name: reverseproxy
    namespace: default
    resourceVersion: "106038"
    uid: a09d7fd2-fb50-488c-9476-de35487ec85c
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        service: reverseproxy
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2022-04-08T11:16:09Z"
        creationTimestamp: null
        labels:
          service: reverseproxy
      spec:
        containers:
        - image: huy56xf/udagram-reverseproxy:v1
          imagePullPolicy: IfNotPresent
          name: reverseproxy
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: default-sa
        serviceAccountName: default-sa
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-04-08T05:55:12Z"
      lastUpdateTime: "2022-04-08T13:03:34Z"
      message: ReplicaSet "reverseproxy-684d9d7f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2022-04-08T14:01:44Z"
      lastUpdateTime: "2022-04-08T14:01:44Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 5
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""